//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `smarthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHouseModule;

/** @hidden */
public class _SmartDevicePrxI extends com.zeroc.Ice._ObjectPrxI implements SmartDevicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
