//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `smarthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHouseModule;

/**
 * Helper class for marshaling/unmarshaling weatherStates.
 **/
public final class weatherStatesHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, WeatherState[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                WeatherState.ice_write(ostr, v[i0]);
            }
        }
    }

    public static WeatherState[] read(com.zeroc.Ice.InputStream istr)
    {
        final WeatherState[] v;
        final int len0 = istr.readAndCheckSeqSize(1);
        v = new WeatherState[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = WeatherState.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<WeatherState[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, WeatherState[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            weatherStatesHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<WeatherState[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            WeatherState[] v;
            v = weatherStatesHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
