// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package events;

public interface ArithmeticOpArgumentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.ArithmeticOpArguments)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 arg1 = 1;</code>
   * @return The arg1.
   */
  int getArg1();

  /**
   * <code>int32 arg2 = 2;</code>
   * @return The arg2.
   */
  int getArg2();
}
