// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package events;

public interface EventInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.EventInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events.EventType eventType = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.events.EventType eventType = 1;</code>
   * @return The eventType.
   */
  events.EventType getEventType();

  /**
   * <code>int32 price = 2;</code>
   * @return The price.
   */
  int getPrice();

  /**
   * <code>repeated string artists = 3;</code>
   * @return A list containing the artists.
   */
  java.util.List<java.lang.String>
      getArtistsList();
  /**
   * <code>repeated string artists = 3;</code>
   * @return The count of artists.
   */
  int getArtistsCount();
  /**
   * <code>repeated string artists = 3;</code>
   * @param index The index of the element to return.
   * @return The artists at the given index.
   */
  java.lang.String getArtists(int index);
  /**
   * <code>repeated string artists = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the artists at the given index.
   */
  com.google.protobuf.ByteString
      getArtistsBytes(int index);
}
