// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package events;

public final class EventsProto {
  private EventsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_ArithmeticOpArguments_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_ArithmeticOpArguments_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_EventInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_EventInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_EventTyeArgument_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_EventTyeArgument_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014events.proto\022\006events\"3\n\025ArithmeticOpAr" +
      "guments\022\014\n\004arg1\030\001 \001(\005\022\014\n\004arg2\030\002 \001(\005\"Q\n\tE" +
      "ventInfo\022$\n\teventType\030\001 \001(\0162\021.events.Eve" +
      "ntType\022\r\n\005price\030\002 \001(\005\022\017\n\007artists\030\003 \003(\t\"8" +
      "\n\020EventTyeArgument\022$\n\teventType\030\001 \001(\0162\021." +
      "events.EventType*6\n\tEventType\022\014\n\010FOOTBAL" +
      "L\020\000\022\013\n\007CONCERT\020\001\022\016\n\nBASKETBALL\020\0022O\n\rEven" +
      "tsService\022>\n\tSubscribe\022\030.events.EventTye" +
      "Argument\032\021.events.EventInfo\"\000(\0010\001B\027\n\006eve" +
      "ntsB\013EventsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_events_ArithmeticOpArguments_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_ArithmeticOpArguments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_ArithmeticOpArguments_descriptor,
        new java.lang.String[] { "Arg1", "Arg2", });
    internal_static_events_EventInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_events_EventInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_EventInfo_descriptor,
        new java.lang.String[] { "EventType", "Price", "Artists", });
    internal_static_events_EventTyeArgument_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_events_EventTyeArgument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_EventTyeArgument_descriptor,
        new java.lang.String[] { "EventType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
