// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package events;

public interface EventTyeArgumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.EventTyeArgument)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events.EventType eventType = 1;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.events.EventType eventType = 1;</code>
   * @return The eventType.
   */
  events.EventType getEventType();
}
